name: BankPlus
version: '${version}'
main: me.pulsi_.bankplus.BankPlus
api-version: 1.13
<<<<<<< HEAD
=======
folia-supported: true
>>>>>>> afb2ba7 (-)
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - Essentials
  - EconomyPlus
  - CMI
authors: [ Pulsi_ ]
load: POSTWORLD
description: The best bank plugin on Spigot!
commands:
  bankplus:
    aliases: [bankp, bank, bp]

  banktop:
    aliases: [btop]